#ifndef EXORCISTS_STATE_H
#define EXORCISTS_STATE_H

typedef enum {
    GATHERING_PROPS,
    WAITING_FOR_FREE_PROPS,
    RESERVING_HOUSE,
    WAITING_FOR_FREE_HOUSE,
    HAUNTING_HOUSE
} state_e;

#endif //EXORCISTS_STATE_H
